POST {{Api_HostAddress}}/auth/register/FacilityWorker
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "FirstName": "Facility",
    "LastName": "Worker",
    "Email": "facility.worker@example.com",
    "Password": "P@ssw0rd"
}
