POST {{Api_HostAddress}}/auth/Register/FacilityManager
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "FirstName": "Fac",
    "LastName": "Manager",
    "Email": "fac.manager@example.com",
    "Password": "P@ssw0rd"
}
