@Api_HostAddress = http://localhost:5123
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJMb2dpc3RpY3NBcHAuRG9tYWluLlNoYXJlZC5BZ2dyZWdhdGVzLlVzZXIuVmFsdWVPYmplY3RzLlVzZXJJZCIsImdpdmVuX25hbWUiOiJKb2huIiwiZmFtaWx5X25hbWUiOiJEb2UiLCJqdGkiOiJiMDcwMDExOS1hZDZkLTRlNDgtOGU4Zi0zZTI4NDk0YjkxNDQiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJCdXNpbmVzc01hbmFnZXIiLCJleHAiOjE3NTk0NTYzNzIsImlzcyI6IkxvZ2lzdGljc0FwcCIsImF1ZCI6IkxvZ2lzdGljc0FwcFVzZXJzIn0.IAfAIlWDlaeEMAR2KIKJqKIsF_G6_uEG3NZsUzhLQ8g
@orderId=52120667-7b0c-4e6c-a4e8-d9f5decedfe7
PUT {{Api_HostAddress}}/Orders/{{orderId}}/status
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "status": "Pending"
}
