PUT {{Api_HostAddress}}/products/{{productId}}/Assortments
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "Assortments": [
        {
            "Color": "Red",
            "Sizes": {
                "s": 1,
                "m": 1,
                "l": 2,
                "xl": 1,
                "xxl": 1
            }
        },
        {
            "Color": "Blue",
            "Sizes": {
                "s": 1,
                "m": 2,
                "l": 2,
                "xl": 2,
                "xxl": 1
            }
        },
        {
            "Color": "Green",
            "Sizes": {
                "s": 1,
                "m": 2,
                "l": 2,
                "xl": 2,
                "xxl": 1
            }
        }
    ]
}