@Api_HostAddress = http://localhost:5123
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJMb2dpc3RpY3NBcHAuRG9tYWluLlNoYXJlZC5BZ2dyZWdhdGVzLlVzZXIuVmFsdWVPYmplY3RzLlVzZXJJZCIsImdpdmVuX25hbWUiOiJKb2huIiwiZmFtaWx5X25hbWUiOiJEb2UiLCJqdGkiOiIyYzE2ODBlMS03NjBlLTRjYjMtODBiZC1jZTFkNWU2YzExZTUiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJCdXNpbmVzc01hbmFnZXIiLCJleHAiOjE3NTkyNjY4NDYsImlzcyI6IkxvZ2lzdGljc0FwcCIsImF1ZCI6IkxvZ2lzdGljc0FwcFVzZXJzIn0.wPiRmvyRtya3wM2lB3bplat0sUH-oe_UnjQPMofLls0
@cartonId=63dc0610-3501-4f0c-be65-993341766b77
DELETE {{Api_HostAddress}}/cartons/{{cartonId}}/cartonItem
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "productId" : "30b39aba-cf2f-454f-83e8-d9b93f410c08",
    "variationId" : "e80036a5-4a79-4e83-925c-14d9ce10fff4",
    "quantity" : 5
}