POST {{Api_HostAddress}}/products/{{productId}}/sizes
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "sizes" : [
        "xs",
        "3xl"
    ],
    "Assortments": [
        {
            "Color": "Red",
            "Sizes": {
                "xs": 1,
                "s": 1,
                "m": 2,
                "l": 2,
                "xl": 2,
                "xxl": 1,
                "3xl": 1
            }
        },
        {
            "Color": "Blue",
            "Sizes": {
                "xs": 1,
                "s": 1,
                "m": 2,
                "l": 2,
                "xl": 2,
                "xxl": 1,
                "3xl": 1
            }
        },
        {
            "Color": "Green",
            "Sizes": {
                "xs": 1,
                "s": 1,
                "m": 2,
                "l": 2,
                "xl": 2,
                "xxl": 1,
                "3xl": 1
            }
        },
        {
            "Color": "White",
            "Sizes": {
                "xs": 1,
                "s": 1,
                "m": 2,
                "l": 2,
                "xl": 2,
                "xxl": 1,
                "3xl": 1
            }
        },
        {
            "Color": "Black",
            "Sizes": {
                "xs": 1,
                "s": 1,
                "m": 2,
                "l": 2,
                "xl": 2,
                "xxl": 1,
                "3xl": 1
            }
        }
    ]
}