POST {{Api_HostAddress}}/products/{{productId}}/colors
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "colors" : [
        "white"
    ],
    "Assortments": [
        {
            "Color": "Red",
            "Sizes": {
                "s": 1,
                "m": 2,
                "l": 2,
                "xl": 2,
                "xxl": 1
            }
        },
        {
            "Color": "Blue",
            "Sizes": {
                "s": 1,
                "m": 2,
                "l": 2,
                "xl": 2,
                "xxl": 1
            }
        },
        {
            "Color": "Green",
            "Sizes": {
                "s": 1,
                "m": 2,
                "l": 2,
                "xl": 2,
                "xxl": 1
            }
        },
        {
            "Color": "White",
            "Sizes": {
                "s": 1,
                "m": 2,
                "l": 2,
                "xl": 2,
                "xxl": 1
            }
        },
        {
            "Color": "Black",
            "Sizes": {
                "s": 1,
                "m": 2,
                "l": 2,
                "xl": 2,
                "xxl": 1
            }
        }
    ]
}