@Api_HostAddress = http://localhost:5123
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJMb2dpc3RpY3NBcHAuRG9tYWluLlNoYXJlZC5BZ2dyZWdhdGVzLlVzZXIuVmFsdWVPYmplY3RzLlVzZXJJZCIsImdpdmVuX25hbWUiOiJKb2huIiwiZmFtaWx5X25hbWUiOiJEb2UiLCJqdGkiOiI3YTczZTk3MC1mZjQ5LTQxNTItYmE3OC1jYjAyZTRjYWUxODEiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJCdXNpbmVzc01hbmFnZXIiLCJleHAiOjE3NTg4OTI0NjIsImlzcyI6IkxvZ2lzdGljc0FwcCIsImF1ZCI6IkxvZ2lzdGljc0FwcFVzZXJzIn0.HfZgPMHWUIHnnISs4kHh56yzWGsHQT_15hoUcZ3DhOs
@warehouseId=bfff4803-2a16-4976-82ab-91e79e178817
POST {{Api_HostAddress}}/warehouse/{{warehouseId}}/rooms
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "roomName" : "Room B"
}