@Api_HostAddress = http://localhost:5123
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJMb2dpc3RpY3NBcHAuRG9tYWluLlNoYXJlZC5BZ2dyZWdhdGVzLlVzZXIuVmFsdWVPYmplY3RzLlVzZXJJZCIsImdpdmVuX25hbWUiOiJKb2huIiwiZmFtaWx5X25hbWUiOiJEb2UiLCJqdGkiOiIxNGQ1YjUxMS0zMzE5LTRiNmMtODZiMy1kNGU4YmNiNjRhNDUiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJCdXNpbmVzc01hbmFnZXIiLCJleHAiOjE3NTg5MzQ1MzQsImlzcyI6IkxvZ2lzdGljc0FwcCIsImF1ZCI6IkxvZ2lzdGljc0FwcFVzZXJzIn0.DmdmZDWesF6c-AFljhAu3L1vTkf3v04PM0WB3I5020o
@warehouseId=bfff4803-2a16-4976-82ab-91e79e178817
GET {{Api_HostAddress}}/Warehouse/{{warehouseId}}
Authorization: Bearer {{token}}