@Api_HostAddress = http://localhost:5123
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJMb2dpc3RpY3NBcHAuRG9tYWluLkFnZ3JlZ2F0ZXMuVXNlci5WYWx1ZU9iamVjdHMuVXNlcklkIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IkRvZSIsImp0aSI6IjRmYWVmYmYxLWQwOTQtNDhlYS05NWI4LWQ2MDZlYTY0NjQ2YSIsImV4cCI6MTc1NzU2MjE0NiwiaXNzIjoiTG9naXN0aWNzQXBwIiwiYXVkIjoiTG9naXN0aWNzQXBwVXNlcnMifQ.0Qu9bhhEQBzkoXBEA-DJ8wd1_f0dkTF0_ZT6V-M0gho
@hostId=abcd
POST {{Api_HostAddress}}/hosts/{{hostId}}/products
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "RefCode": "PROD-001",
    "Season": "SS2024",
    "Name": "Summer T-Shirt",
    "Description": "A light and comfortable t-shirt perfect for summer.",
    "IsActive": true,
    "Categories": ["Men"],
    "Colors": ["Red", "Blue", "Green"],
    "Sizes": ["S", "M", "L", "XL", "XXL"],
    "Assortments": [
        {
            "Color": "Red",
            "Sizes": {
                "s": 1,
                "m": 2,
                "l": 2,
                "xl": 2,
                "xxl": 1
            }
        },
        {
            "Color": "Blue",
            "Sizes": {
                "s": 1,
                "m": 2,
                "l": 2,
                "xl": 2,
                "xxl": 1
            }
        },
        {
            "Color": "Green",
            "Sizes": {
                "s": 1,
                "m": 2,
                "l": 2,
                "xl": 2,
                "xxl": 1
            }
        }
    ]
}
