@Api_HostAddress = http://localhost:5123

GET {{Api_HostAddress}}/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3YWNjYTI3Ni05NzIxLTQ1MzMtODg1MS04NTBhYTI0ZDdiYWIiLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiRG9lIiwianRpIjoiZGU5NmRhODQtMDAxYy00MjljLWFmYTEtNDkxMGE5ZjMwZGI5IiwiZXhwIjoxNzU3MDE0NTkxLCJpc3MiOiJMb2dpc3RpY3NBcHAiLCJhdWQiOiJMb2dpc3RpY3NBcHBVc2VycyJ9.Cp9dmDbyh4sZcmYlhwMDrT6kj9lHHcrr0aEaV1vWpn4