@Api_HostAddress = http://localhost:5123
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJMb2dpc3RpY3NBcHAuRG9tYWluLkFnZ3JlZ2F0ZXMuVXNlci5WYWx1ZU9iamVjdHMuVXNlcklkIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IkRvZSIsImp0aSI6ImM1YTZkMTcwLTU4MzktNGNkZC05MTFhLTQ3Yzk4YWY1YWIwOCIsImV4cCI6MTc1ODUwMTY1NSwiaXNzIjoiTG9naXN0aWNzQXBwIiwiYXVkIjoiTG9naXN0aWNzQXBwVXNlcnMifQ.ys85HMqcC_JZMKtxASXpCAM7n1uADdz_rAlANx_OW9c
@hostId=abcd
GET {{Api_HostAddress}}/hosts/{{hostId}}/products
Authorization: Bearer {{token}}
