@Api_HostAddress = http://localhost:5123
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJMb2dpc3RpY3NBcHAuRG9tYWluLlNoYXJlZC5BZ2dyZWdhdGVzLlVzZXIuVmFsdWVPYmplY3RzLlVzZXJJZCIsImdpdmVuX25hbWUiOiJKb2huIiwiZmFtaWx5X25hbWUiOiJEb2UiLCJqdGkiOiI5MDc4NmQwZC05MTQyLTQwNzctYjNhMS1mZDA0NWJhY2NmNzYiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJCdXNpbmVzc01hbmFnZXIiLCJleHAiOjE3NTk0NDYwOTgsImlzcyI6IkxvZ2lzdGljc0FwcCIsImF1ZCI6IkxvZ2lzdGljc0FwcFVzZXJzIn0.hU-rKKJ2wyI2JyBuVmXfQGnl7UOsAIUMAMAItgVnqJU
POST {{Api_HostAddress}}/OrderReturns
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "orderId": "b32e7a48-5d2c-4fe7-a41c-6a6aa7c0cdca",
    "orderItemIds": ["ebd06d8d-eee2-43b0-9cfe-dd734c2a3ba7"]
}
